### ISSUE TITLE
can join "waiting for server" fake event

### ISSUE THREAD

**Issue by ejolson9** [Collabify/Collabify_App#32]

**Comment by amcolash** [comment]
Maybe set a state and then on a successful pull of events change the state, whenever trying to join check if in the "loading" state...

Edit:
Will try to implement a fix to this if I get some time in the next few days

**Comment by amcolash** [comment]
Will try to implement a fix to this if I get some time in the next few days

**Comment by amcolash** [comment]
Fixed in #33
