### ISSUE TITLE
dj starts with playlist 

### ISSUE THREAD

**Issue by ejolson9** [Collabify/Collabify_App#38]
probably just need to change logic in DjActivity -> override the on update request, or otherwise change logic

**Comment by ejolson9** [comment]
This may have been unclear, but issue is that the dj was opening to a playlist when it should really be an empty playlist  as it was just created

**Comment by amcolash** [comment]
Whoops, I think we also talked about this feature of opening to a playlist. Guess a useful feature none-the-less ;)
